# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Project
    url: about/
    weight: 20
    identifier: Project  


  - name: Project_1
    parent: Project      
    pageRef: project    
    weight: 21

  
  - name: Project_2
    parent: Project
    pageRef: publication 
    weight: 22

  
  - name: Contact
    url: /contact/
    weight: 23